# scripts/install-backup-schedule.ps1
#
# T0.1 — Optional convenience: register a Windows Task Scheduler entry that
# runs scripts/backup-db.ps1 daily at 03:00 local time.
#
# This script is NOT run automatically. Run it yourself when you want daily
# backups armed:
#
#   pwsh -File ./scripts/install-backup-schedule.ps1
#
# To remove the schedule later:
#
#   Unregister-ScheduledTask -TaskName 'sol-pump-radar daily backup' -Confirm:$false
#
# Notes:
# - No elevation required: this registers under the current user, not the
#   system. It runs only while you're logged in.
# - If Docker Desktop is not running at 03:00, the backup script will exit 1
#   and you'll see it in backup.log (it does not silently fail).
# - Requires PowerShell 5+ (Windows built-in) or pwsh.

param(
  [string]$TaskName = 'sol-pump-radar daily backup',
  [string]$Time = '03:00',
  [string]$BackupDir = $(if ($env:BACKUP_DIR) { $env:BACKUP_DIR } else { Join-Path $HOME 'OneDrive\sol-pump-radar-backups' })
)

$ErrorActionPreference = 'Stop'
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$BackupScript = Join-Path $ProjectRoot 'scripts\backup-db.ps1'

if (-not (Test-Path $BackupScript)) {
  Write-Host "ERROR: $BackupScript not found"
  exit 1
}

# Use powershell.exe (Windows PowerShell 5.1) for broadest compatibility on
# Windows 10/11 without requiring pwsh install. Switch to pwsh.exe if you
# prefer PowerShell 7+.
$Action = New-ScheduledTaskAction `
  -Execute 'powershell.exe' `
  -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$BackupScript`" -Dest `"$BackupDir`"" `
  -WorkingDirectory $ProjectRoot

$Trigger = New-ScheduledTaskTrigger -Daily -At $Time

# Run as the current user, not SYSTEM (Docker Desktop and the user profile
# must be available; SYSTEM has no Docker context).
$Principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive

# Realistic settings: don't double-run if Docker is slow; allow running on
# battery (laptop); end task if it hangs > 30 min.
$Settings = New-ScheduledTaskSettingsSet `
  -StartWhenAvailable `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -ExecutionTimeLimit (New-TimeSpan -Minutes 30) `
  -MultipleInstances IgnoreNew

# Replace any existing task with the same name (idempotent install)
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask `
  -TaskName $TaskName `
  -Action $Action `
  -Trigger $Trigger `
  -Principal $Principal `
  -Settings $Settings `
  -Description "Daily pg_dump of solpump → $BackupDir. Generated by scripts/install-backup-schedule.ps1." | Out-Null

Write-Host ""
Write-Host "Installed:   $TaskName"
Write-Host "Runs daily:  $Time (current user only — won't fire if you're logged out)"
Write-Host "Dest:        $BackupDir"
Write-Host "Manual run:  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "Remove:      Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
