/** Transactional integration check using connection-local temporary tables only. */
import assert from "node:assert/strict";
import type { PoolClient } from "pg";
import { getPool } from "@spr/db";
import {
  paperConfigFromEnv,
  researchBuy,
  researchCensor,
  researchClose,
  researchCloseAtMark,
  researchFailureFee,
} from "@spr/trading";
import { buyAt, sellAt } from "@/lib/strategies/pool";
import { CURVE_K } from "@/lib/strategies/catalog";

async function main() {
  const pool = getPool(), client = await pool.connect();
  const transaction = async <T>(fn: (client: PoolClient) => Promise<T>) => fn(client);
  try {
    await client.query("BEGIN");
    for (const table of ["paper_positions", "paper_trade_fills", "paper_portfolio", "auto_sessions", "domain_events", "research_episodes"]) {
      await client.query(`CREATE TEMP TABLE ${table} (LIKE public.${table} INCLUDING DEFAULTS) ON COMMIT DROP`);
      if (["paper_positions", "paper_trade_fills", "domain_events"].includes(table)) {
        await client.query(`ALTER TABLE ${table} ALTER COLUMN id DROP DEFAULT`);
        await client.query(`ALTER TABLE ${table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`);
      }
    }
    await client.query("INSERT INTO paper_portfolio(id,session_id,balance_sol,equity_sol,peak_equity_sol) VALUES(1,9001,10,10,10)");
    await client.query("INSERT INTO auto_sessions(id,mode,status,params,stats) VALUES(9002,'paper','active','{}','{}')");
    const state = { x: 60, k: CURVE_K }, size = 0.349, tx = 0.000055;
    const config = { ...paperConfigFromEnv(), maxPositionSol: 0.70, maxOpenPositions: 3, dailyLossLimitSol: 1 };
    const fill = buyAt(state,size,0,undefined,0.0055);
    const input = { mint:"ResearchTestMint",key:"research:test:entry",autoSessionId:"9002",maxConcurrent:3,dailyLossCap:1,
      features:{research_strategy:"scaleIn",session_id:"9002",research_footprint:fill.intoPool},
      fill:{price:60,tokens:fill.tokens,cash:size+tx,fee:size*0.0125+tx,ts:Date.now()/1000} };
    const opened = await researchBuy(input,config,transaction);
    assert.equal(opened.ok,true);
    if (!opened.ok) throw new Error(opened.reason);
    assert.equal((await researchBuy(input,config,transaction)).ok,true);
    assert.equal(Number((await client.query("SELECT count(*) FROM paper_positions")).rows[0].count),1);
    const afterBuy = Number((await client.query("SELECT balance_sol FROM paper_portfolio")).rows[0].balance_sol);
    assert.ok(Math.abs(afterBuy - (10-size-tx)) < 1e-10);
    const add = buyAt(state,size,fill.intoPool,undefined,0.0055);
    const addInput = {...input,key:"research:test:add",addTo:opened.id,
      features:{...input.features,research_footprint:fill.intoPool+add.intoPool},
      fill:{...input.fill,tokens:add.tokens} };
    assert.equal((await researchBuy(addInput,config,transaction)).ok,true);
    assert.equal((await researchBuy(addInput,config,transaction)).ok,true);
    const position = (await client.query("SELECT quantity,notional_sol FROM paper_positions")).rows[0];
    assert.ok(Math.abs(position.quantity - fill.tokens - add.tokens) < 1e-6);
    assert.ok(Math.abs(position.notional_sol - 2*(size+tx)) < 1e-10);
    assert.equal(Number((await client.query("SELECT count(*) FROM paper_trade_fills")).rows[0].count),2);
    const proceeds = sellAt(state,position.quantity,fill.intoPool+add.intoPool,undefined,0.0055)-tx;
    const close = await researchClose({id:opened.id,price:60,proceeds,fee:tx,reason:"research_timer",ts:Date.now()/1000},transaction);
    assert.equal(close.ok,true);
    assert.equal((await researchClose({id:opened.id,price:60,proceeds,fee:tx,reason:"research_timer",ts:Date.now()/1000},transaction)).ok,false);
    const after = (await client.query("SELECT balance_sol,realized_pnl_sol FROM paper_portfolio")).rows[0];
    assert.ok(Math.abs(after.balance_sol - 10 - after.realized_pnl_sol) < 1e-10);
    assert.ok(after.realized_pnl_sol < 0, "still-market round trip must lose its full costs");
    assert.equal(Number((await client.query("SELECT count(*) FROM paper_trade_fills")).rows[0].count),3);
    const markedInput = { ...input, key: "research:test:marked" };
    const marked = await researchBuy(markedInput, config, transaction);
    assert.equal(marked.ok, true);
    if (!marked.ok) throw new Error(marked.reason);
    const markedAt = Date.now();
    await client.query(
      `UPDATE paper_positions SET current_price=61,unrealized_pnl_sol=0.01,
         entry_features=entry_features || $1::jsonb WHERE id=$2`,
      [JSON.stringify({ research_mark_pnl: 0.01, price_at_ms: markedAt, research_mark_exit_fee: tx }), marked.id],
    );
    const markedClose = await researchCloseAtMark({ id: marked.id, reason: "manual_demo", ts: markedAt / 1000 }, transaction);
    assert.equal(markedClose.ok, true);
    if (!markedClose.ok) throw new Error(markedClose.reason);
    assert.ok(Math.abs(markedClose.pnl - 0.01) < 1e-10);

    const censoredInput = { ...input, key: "research:test:censored" };
    const censoredOpen = await researchBuy(censoredInput, config, transaction);
    assert.equal(censoredOpen.ok, true);
    if (!censoredOpen.ok) throw new Error(censoredOpen.reason);
    const beforeCensor = Number((await client.query("SELECT balance_sol FROM paper_portfolio")).rows[0].balance_sol);
    const censored = await researchCensor({ id: censoredOpen.id, reason: "no exit tape", ts: Date.now() / 1000 }, transaction);
    assert.equal(censored.ok, true);
    const afterCensor = Number((await client.query("SELECT balance_sol FROM paper_portfolio")).rows[0].balance_sol);
    assert.ok(Math.abs(afterCensor - beforeCensor - (size + tx)) < 1e-10);
    const censoredRow = (await client.query("SELECT state,realized_pnl_sol,close_reason FROM paper_positions WHERE id=$1", [censoredOpen.id])).rows[0];
    assert.equal(censoredRow.state, "CLOSED");
    assert.equal(censoredRow.realized_pnl_sol, null);
    assert.equal(censoredRow.close_reason, "research_censored");
    // No phantom fills when budget, account mode, or active-session constraints reject an entry.
    const capReject = await researchBuy({...input,key:"too-large"},{...config,maxPositionSol:0.25},transaction);
    assert.equal(capReject.ok,false);
    await client.query("UPDATE auto_sessions SET mode='live'");
    assert.equal((await researchBuy({...input,key:"live-reject"},config,transaction)).ok,false);
    await client.query("UPDATE auto_sessions SET mode='paper',status='stopped'");
    assert.equal((await researchBuy({...input,key:"stopped-reject"},config,transaction)).ok,false);
    await client.query("INSERT INTO research_episodes(session_id,episode_key,mint,strategy,decision_ts,status,reason) VALUES(9002,'failed','m','curveLadder',now(),'NO_FILL','test')");
    const beforeFailure = Number((await client.query("SELECT balance_sol FROM paper_portfolio")).rows[0].balance_sol);
    await researchFailureFee({sessionId:"9002",key:"failed",fee:tx},transaction);
    await researchFailureFee({sessionId:"9002",key:"failed",fee:tx},transaction);
    const failed = (await client.query("SELECT balance_sol,realized_pnl_sol FROM paper_portfolio")).rows[0];
    assert.ok(Math.abs(failed.balance_sol - (beforeFailure-tx)) < 1e-10);
    assert.ok(Math.abs(failed.balance_sol - 10 - failed.realized_pnl_sol) < 1e-10);
    console.log("PASS: real Postgres transactions, exact entry/add/exit and marked-manual-close accounting, neutral terminal censoring, duplicate protection, risk cap, paper-only and stopped-session guards, failure fees. Production data unchanged.");
  } finally { await client.query("ROLLBACK"); client.release(); await pool.end(); }
}
void main().catch((e) => { console.error(e); process.exitCode=1; });
